language: rust
os:
  - linux
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - name: System Library
      addons:
        apt:
          packages:
            - libhunspell-dev
          update: true
    - name: Bundled Library
